etcd-io/etcd-operator

.devcontainer/devcontainer.json, .devcontainer/post-install.sh, .github/workflows/test-e2e.yml, .github/workflows/test.yml, Dockerfile, README.md, go.mod
Let's try and keep the operator aligned with our other etcd-io projects.
-  Use go version from go.mod in actions workflows.
- Update to go 1.23.
- Align devcontainer with `etcd-io/etcd`.
=> Update to go 1.23

.gitignore, Makefile, docs/api-references/config.yaml, docs/api-references/docs.md, docs/api-references/template/gv_details.tpl, docs/api-references/template/gv_list.tpl, docs/api-references/template/type.tpl, docs/api-references/template/type_members.tpl
Add etcd-operator api documentation, reference tool: https://github.com/elastic/crd-ref-docs
We can `make api-docs` to generate the latest api documentation.
Preview: [docs.md](https://github.com/etcd-io/etcd-operator/blob/fef3297b4564d0a6a8469e68f399147650b5c44e/docs/api-references/docs.md)
=> feat: add api docs

.github/dependabot.yml, .github/workflows/test-e2e.yml, .github/workflows/test.yml, Dockerfile
=> Add Dependabot config for weekly updates

internal/controller/etcdcluster_controller.go
=> Some minor enhancement & cleanup on the reconcile process

internal/controller/etcdcluster_controller.go, internal/controller/utils.go, internal/controller/utils_test.go, internal/etcdutils/etcdutils.go, internal/etcdutils/etcdutils_test.go, test/e2e/e2e_test.go
This pull request fixes the lint error on the workflow.
cf. https://github.com/etcd-io/etcd-operator/actions/runs/12767437613/job/35585812805
* [`internal/controller/etcdcluster_controller.go`](diffhunk://#diff-7e023adf1c245d768f95e3f174cab882db08efd47023a9ce81e29a3a7767c12aL24-L26): Reorganized import statements to improve readability and maintainability. 
* [`internal/controller/utils.go`](diffhunk://#diff-2e75daf7fbfd686a57f8e7bd14cb6e04c7ca3ffb3406fa0f702641c72ff12b3dL12-L14): Reorganized import statements to improve readability and maintainability. 
* [`internal/controller/utils_test.go`](diffhunk://#diff-429334b066a97ed558217b47f55a1fc71836df740243033b9a4a6ac1829b12e5L11-L14): Reorganized import statements to improve readability and maintainability. 
* …
=> Chore: Fix lint error

Dockerfile
Ensure golang patch version is specified.
Base of Debian Bookworm in line with other etcd projects.
Addresses: https://github.com/etcd-io/etcd-operator/pull/37#discussion_r1914896599
cc @ahrtr
=> Align Dockerfile builder image

Dockerfile, go.mod, tools/mod/go.mod
etcd-operator: update golang toolchain to 1.23.5
Subtask from Issue: https://github.com/etcd-io/etcd/issues/19210
1. Retrieve `golang:1.23.5-bookworm` digest from docker hub (use the list-manifest for make to work would work with multi-arch):
```
TOKEN=$(curl -s "https://auth.docker.io/token?service=registry.docker.io&scope=repository:library/golang:pull" | jq -r .token)
curl -s -I -H "Authorization: Bearer $TOKEN" -H "Accept: application/vnd.docker.distribution.manifest.list.v2+json" "https://registry.hub.docker.com/v2/library/golang/manifests/1.23.5-bookworm" | grep -i "Docker-Content-Digest"
```
2. Verify able to build and run unit-tests as -
```
make build
make docker-build
make test
```
=> Update golang toolchain to 1.23.5

.github/workflows/gh-workflow-approve.yml
Allow to run github workflows for PRs which have ok-to-test labels
Fixes #43
=> github workflow: enable workflow approval

pkg/certificate/auto/doc.go, pkg/certificate/cert-manager/doc.go, pkg/certificate/interface.go
See the [Spec & Design doc](https://docs.google.com/document/d/1k8os77Hqxe36nUaZ31YqBGBuXcgdozVPppJYOfwUDFA/edit?tab=t.0)
cc @hakman @gdasson @ArkaSaha30 
also cc @jberkus @jmhbnz @justinsb
=> Add the initial scaffold of certificate management

Dockerfile, go.mod, tools/mod/go.mod
Updating golang toolchain to version 1.23.6
Subtask of https://github.com/etcd-io/etcd/issues/19333
Verified with
```
make build
make docker-build
make test
```
=> Update golang toolchain to version 1.23.6

pkg/certificate/certificate.go, pkg/certificate/interfaces/interface.go
Each provider implementation (i.e. auto, cert-manager) needs to depend on the interface. The certificate framework depends on the interface, but it shouldn't depend on the each implementation based on the [Dependency Inversion Principle](https://en.wikipedia.org/wiki/Dependency_inversion_principle). 
Both the framework and each implementation shouldn't depend on each other, instead both of them should only depend on the interface(abstract). So move the interface into a dedicated package.
cc @ArkaSaha30 @hakman @jmhbnz @justinsb @neolit123
=> Move certificate interface into dedicated package to avoid cycle dependency

test/e2e/e2e_suite_test.go
The make `kustomize` and `controller-gen` targets are prerequisites of the targets later called in the e2e tests (`controller-gen` from `manifests`, and `kustomize` from `install`), so there's no need to trigger them manually.
=> Remove unnecessary make command to install tools in e2e tests

Makefile, test/e2e/e2e_suite_test.go
Follow up from: https://github.com/etcd-io/etcd-operator/pull/72#discussion_r1957068496
And restore the Apache License header.
=> Remove make manifests from e2e tests

internal/controller/utils.go, internal/controller/utils_test.go
using `wait.ExponentialBackoffWithContext` to refactor `waitForStatefulSetReady` function.
=> cleanup: refactor code with wait.ExponentialBackoffWithContext

test/utils/utils.go
This PR removes all dependencies on and references to Ginkgo in the utils package file.
=> Remove gingko from test/utils

Makefile
Installing via `go get`/`go install` is discouraged by the golangci-lint manual. Reference:
https://golangci-lint.run/welcome/install/#install-from-sources
We're not bound to the host Go version if we install using their preferred method. And in cases like Prow where updates to the base image take longer, this could slow down Go version upgrades.
=> Update golangci-lint installation to use installation script

Dockerfile, README.md, go.mod, tools/mod/go.mod
Upgrades Go to 1.24.0.
Part of etcd-io/etcd#19417.
=> Bump go to 1.24.0

.devcontainer/devcontainer.json
Update dev container to Go 1.24. Currently, MS has only support to a dev version with Go 1.24 in their registry.
=> Update dev container to Go 1.24

.golangci.yml, Makefile, go.mod, go.sum, internal/controller/etcdcluster_controller_test.go, internal/controller/suite_test.go, internal/controller/utils_test.go
This PR refers to the [idea](https://github.com/etcd-io/etcd-operator/issues/19#issuecomment-2670923301) to remove `Ginkgo` entirely from the `etcd-operator` project. 
We removed Ginkgo instances from: 
- etcd controller tests
- golangci.yaml
=> Remove usage of ginkgo entirely

Dockerfile, README.md, go.mod, tools/mod/go.mod
Relates to https://github.com/etcd-io/etcd/issues/19524
fixes #91
/cc @ivanvc @ahrtr
=> chore: bump golang to 1.24.1

Makefile, scripts/release.sh
The release script does the following:
1. Generates the distribution YAML file and places it in the default location `dist/install.yaml`. Then, it commits the file to the repository.
2. Creates a tag and pushes it to the repository.
3. Builds the Docker image and pushes to the registry.
These steps are idempotent, so if the script fails, it can be resumed and skip what already succeeded.
I tested this in my fork and pushed to my registry.
1. It generates the distribution YAML, this is the commit: https://github.com/ivanvc/etcd-operator/commit/7d3d4b8d1e6831bcdfbd9d612bbffc8c8f0a7c40
2. It pushed the tag: https://github.com/ivanvc/etcd-operator/releases/tag/v0.1.0 (pointing to that commit)
3. This is the image it pushed: https://hub.docker.com/repository/docker/ivan/etcd-operator/tags/v0.1. …
=> Add release script

internal/controller/utils.go
When `ec.Spec.StorageSpec.AccessModes` is empty, or not configured at all, we should defaults to `corev1.ReadWriteOnce`. The current implementation is just to set an empty string.
Still we should add test for the storage.
cc @ivanvc @gdasson
=> Defaults to ReadWriteOnce when it's empty or not provided

Dockerfile, go.mod, tools/mod/go.mod
Reference https://github.com/etcd-io/etcd/issues/19713
=> Bump go toolchain to v1.24.2

api/v1alpha1/etcdcluster_types.go, config/crd/bases/operator.etcd.io_etcdclusters.yaml, config/manager/kustomization.yaml, config/samples/operator_v1alpha1_etcdcluster.yaml, internal/controller/etcdcluster_controller.go, test/e2e/e2e_test.go
This PR adds:
* minimum cluster size of 0 members
* generate CRD
* add defaults to config/samples  manifest
=> Add cluster size validation marker

api/v1alpha1/etcdcluster_types.go, config/crd/bases/operator.etcd.io_etcdclusters.yaml, config/samples/operator_v1alpha1_etcdcluster.yaml, internal/controller/etcdcluster_controller.go, internal/controller/etcdcluster_controller_test.go, test/e2e/e2e_test.go
After discussions, it has been decided that a minimum cluster size is `1`. 
This PR sets the spec marker validation, as well as adjusts its tests to check whether the api server returns anything other than `errors.Invalid()`.
It also deprecates the code where controller logs and quits when cluster size is set to zero. This condition will never happen, as CEL validation will not allow the CR to be persisted.
=> etcd-operator: minimum size cluster validation

internal/controller/suite_test.go
see https://github.com/etcd-io/etcd-operator/pull/143#issuecomment-2890241826
see @ivanvc @jmhbnz @frederiko @abdurrehman107 
New output of the test:
```
=== RUN   TestControllerReconcile
etcdcluster_controller_test.go:46: Checking for EtcdCluster resource
etcdcluster_controller_test.go:49: Creating EtcdCluster resource
{"level":"info","ts":"2025-05-19T10:15:15+01:00","msg":"Reconciling EtcdCluster","spec":{"size":1,"version":""}}
{"level":"info","ts":"2025-05-19T10:15:15+01:00","msg":"Creating StatefulSet with 0 replica","expectedSize":1}
{"level":"info","ts":"2025-05-19T10:15:15+01:00","msg":"Now updating configmap","name":"test-etcd-cluster-state","namespace":"default"}
{"level":"info","ts":"2025-05-19T10:15:15+01:00","msg":"Now creating/updating …
```
=> Set logger for unit test

internal/controller/utils_test.go, internal/etcdutils/etcdutils_test.go
This PR adds GO usetesting, to be aligned with [etcd](https://github.com/etcd-io/etcd) repo.
The directive itself will be added in a follow-up PR, not to fail the CI workflow.
cc @ahrtr @ivanvc
=> chore: use Go usetesting

.golangci.yml
This PR enables usetesting linter directive.
Follow up of https://github.com/etcd-io/etcd-operator/pull/162
cc @ahrtr @ivanvc
=> chore: enable usetesting linter directive

internal/controller/utils.go, internal/controller/utils_test.go
This small refactor proposes deprecating prepareOwnerReferences in favor of controllerutils.SetControllerReference.
=> Deprecate prepareOwnerReference in favor of controllerutils

Makefile
Implements a minimal version of setting the `GOTOOLCHAIN` environment similar to what we have in etcd: https://github.com/etcd-io/etcd/commit/e094139b05244c5eab0e62172f92ac5e90feb73b.
Part of https://github.com/etcd-io/etcd/issues/20576.
Unblocks #196.
=> Set `GOTOOLCHAIN` environment variable

test/e2e/e2e_test.go, test/e2e/helpers_test.go
This PR **extends the E2E suite under `test/e2e/`** with realistic cluster-lifecycle scenarios, **PVC-backed clusters**, and shared helpers to reduce duplication and flakiness. It adds **scaling**, **pod recovery with persistent storage**, and **KV/replication** checks using `etcdctl` **from inside cluster pods**.
**No controller or production code changes** are included.
* **`test/e2e/e2e_test.go`**
* Keeps existing `TestInvalidClusterSize`, `TestClusterHealthy`.
* **New:** `TestScaling` (table-driven: `ScaleInFrom3To1`, `ScaleOutFrom1To3`)
* Verifies the controller updates **StatefulSet replicas**.
* Checks etcd **member list** count and ensures **no learners** remain after scaling.
* **New:** `TestPodRecovery`
* Starts a **3-node PVC-backed** cluster, deletes one pod, waits for …
=> test(e2e): add scaling & KV functionality tests; extract shared helpers
